number1=input('Enter number1')
number2=input('Enter number2')
print(number1,number2)

number1=input('Enter number1')
number2=input('Enter number2')
sum=number1+number2
print(sum)

number1=input('Enter number1')
number2=input('Enter number2')
addition=int(number1)+int(number2)
print(addition)
subtraction=int(number1)-int(number2)
print(subtraction)
division=int(number1)/int(number2)
print(division)
multiplication=int(number1)*int(number2)
print(multiplication)

print(math.acos(.).)
print(math.acosh(.).)
print(math.asin(.).)
print(math.asinh(.).)
print(atan(.).)
print(math.atan2(.).)
print(math.atanh(.).)
print(math.ceil(.).)
print(math.ceil(.).)
print(math.comb(.).)
